openapi: 3.0.0
info:
  title: Hello World API
  description: A simple API that returns "Hello World!"
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
paths:
  /hello:
    get:
      summary: Get a "Hello World!" message
      operationId: getHelloWorld
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: Hello World!
